name: Build Check

on:
  push:
    branches:
      - master
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    branches:
      - master
    paths:
      - '**.java'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build backend with Maven
        run: mvn clean verify

#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '18'
#
#      - name: Build frontend
#        run: |
#          cd frontend
#          npm install
#          npm run build